#!/bin/bash

# support for strings/typeof in named sets.
# s1 and s2 are identical, they just use different
# ways for declaration.

EXPECTED="table inet t {
	set s1 {
		typeof osf name
		elements = { \"Linux\" }
	}

	set s2 {
		typeof vlan id
		elements = { 2, 3, 103 }
	}

	set s3 {
		typeof meta ibrpvid
		elements = { 2, 3, 103 }
	}

	chain c1 {
		osf name @s1 accept
	}

	chain c2 {
		ether type vlan vlan id @s2 accept
	}
}

table bridge t {
       set s3 {
               typeof meta ibrpvid
               elements = { 2, 3, 103 }
       }

       set s4 {
               typeof vlan id . ip saddr
               elements = { 3567 . 1.2.3.4 }
       }

       set s5 {
               typeof meta ibrpvid . ip saddr
               elements = { 3567 . 1.2.3.4 }
       }

       chain c3 {
               meta ibrpvid @s3 accept
       }

       chain c4 {
               ether type vlan vlan id . ip saddr @s4 accept
       }

       chain c4a {
               meta ibrpvid . ip saddr @s4 accept
       }

       chain c5 {
               meta ibrpvid . ip saddr @s5 accept
       }

       chain c5a {
               ether type vlan vlan id . ip saddr @s5 accept
       }
}"

set -e
$NFT -f - <<< $EXPECTED

