#!/bin/bash

# support for strings/typeof in named sets.
# s1 and s2 are identical, they just use different
# ways for declaration.

EXPECTED="table inet t {
	set s1 {
		type typeof(osf name)
		elements = { \"Linux\" }
	}

	set s2 {
		type string, 128
		elements = { \"Linux\" }
	}

	set s3 {
		type typeof(vlan id)
		elements = { 2, 3, 103 }
	}

	set s4 {
		type integer,16
		elements = { 2, 3, 103, 2003 }
	}
	chain c1 {
		osf name @s1 accept
		osf name @s2 accept
	}

	chain c2 {
		ether type vlan vlan id @s3 accept
		ether type vlan vlan id @s4 accept
	}
}"

set -e
$NFT -f - <<< $EXPECTED

